### ISSUE TITLE
Heruko App Crashed beim Vorlesungscode. Warum auch immer.

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2#321]
Hallo,

da es nicht mit meinem EisDealer Code funktioniert hatte, habe ich etwas rum probier und dabei versucht den Vorlesungs Code für meine heruko App umzubauen, dabei habe ich nur die Links geändert, und dann alles deployed. Blöderweise crashed die App immer wenn ich sie öffne. Die Logs spucken folgendes aus: 

2019-05-01T15:31:38.672247+00:00 heroku[web.1]: Starting process with command `npm start`
2019-05-01T15:31:41.851358+00:00 heroku[web.1]: State changed from starting to crashed
2019-05-01T15:31:41.831262+00:00 heroku[web.1]: Process exited with status 1
2019-05-01T15:31:41.554488+00:00 app[web.1]: 
2019-05-01T15:31:41.554508+00:00 app[web.1]: > miniserver@1.0.0 start /app
2019-05-01T15:31:41.554510+00:00 app[web.1]: > node Aufgabe_6/Client/SendData.js
2019-05-01T15:31:41.554511+00:00 app[web.1]: 
2019-05-01T15:31:41.620423+00:00 app[web.1]: /app/Aufgabe_6/Client/SendData.js:5
2019-05-01T15:31:41.620427+00:00 app[web.1]:     window.addEventListener("load", init);
2019-05-01T15:31:41.620428+00:00 app[web.1]:     ^
2019-05-01T15:31:41.620430+00:00 app[web.1]: 
2019-05-01T15:31:41.620431+00:00 app[web.1]: ReferenceError: window is not defined
2019-05-01T15:31:41.620433+00:00 app[web.1]:     at /app/Aufgabe_6/Client/SendData.js:5:5
2019-05-01T15:31:41.620434+00:00 app[web.1]:     at Object.<anonymous> (/app/Aufgabe_6/Client/SendData.js:35:3)
2019-05-01T15:31:41.620440+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:759:30)
2019-05-01T15:31:41.620441+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-05-01T15:31:41.620442+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:628:32)
2019-05-01T15:31:41.620444+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
2019-05-01T15:31:41.620445+00:00 app[web.1]:     at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
2019-05-01T15:31:41.620447+00:00 app[web.1]:     at internal/main/run_main_module.js:17:11
2019-05-01T15:31:41.635877+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-05-01T15:31:41.636662+00:00 app[web.1]: npm ERR! errno 1
2019-05-01T15:31:41.638777+00:00 app[web.1]: npm ERR! miniserver@1.0.0 start: `node Aufgabe_6/Client/SendData.js`
2019-05-01T15:31:41.639043+00:00 app[web.1]: npm ERR! Exit status 1
2019-05-01T15:31:41.639418+00:00 app[web.1]: npm ERR! 
2019-05-01T15:31:41.639702+00:00 app[web.1]: npm ERR! Failed at the miniserver@1.0.0 start script.
2019-05-01T15:31:41.639973+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-01T15:31:41.648232+00:00 app[web.1]: 
2019-05-01T15:31:41.648441+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-05-01T15:31:41.648583+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-05-01T15_31_41_642Z-debug.log
2019-05-01T15:31:43.869446+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ios-eia2.herokuapp.com request_id=465a484a-0112-4920-ac36-6c8656d6a4ed fwd="84.176.22.206" dyno= connect= service= status=503 bytes= protocol=https

Link zu dem Repo: https://github.com/ivenios/EIA2/tree/master/Aufgabe_6/Client

**Comment by ivenios** [comment]
Die Server.js bekomme ich zum laufen.

**Comment by R4Pi3R** [comment]
Bin gerade unterwegs und kann es daher nicht ausführlicher nachschauen, aber für mich sieht das aus als versuchst du den Client auf dem Server zum laufen zu bringen, oder?

**Comment by Plagiatus** [comment]
sieht für mich genauso aus. Und wenn du die Server.js zum laufen bekommst, wo ist dann das Problem?

Der Client Code soll weiterhin auf dem Client laufen, der Server Code jetzt auf dem Server.

**Comment by ivenios** [comment]
achso, arg, danke. Macht ja Sinn. Danke.
